### ISSUE TITLE
Markdown preview

### ISSUE THREAD

**Issue by LorPapa** [DrBenghi/IlCorso#26]
Gentile professor benghi,

volevo chiederle come fare a visualizzare la preview del mio file in una repository?

https://github.com/LorPapa/G-Maietta-Papa/blob/main/Normative/Posa

Da atom sono in grado di vedere ad esempio anche l'immagine che ho aggiunto ma da github vedo solo il codice tipo "raw".

**Comment by CBenghi** [comment]
Risolto in presenza con lo studente
